---
title: "RWA analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

rwa_clean <- read_csv("clean_data/rwa_clean.csv")
```


# 1. What’s the average RWA score for each gender?
```{r}
rwa_clean %>% 
  group_by(gender) %>% 
  summarise(mean_rwa = mean(rwa, na.rm = T))
```


# 2. What’s the average RWA score for left handed people vs. right handed people?
```{r}
rwa_clean %>% 
  group_by(hand) %>% 
  summarise(mean_rwa = mean(rwa, na.rm = T))
```


# 3. What’s the average family size for each type of childhood?
```{r}
rwa_clean %>% 
  group_by(urban) %>% 
  summarise(mean_fam_size = mean(familysize, na.rm = T))
```



# 4. What’s the average time to take the test for each education level?
```{r}
rwa_clean %>% 
  group_by(education) %>% 
  summarise(mean_time = mean(testelapse, na.rm = T))
```



# 5. Create a plot of results of question 4.
```{r}
rwa_clean %>% 
  group_by(education) %>% 
  summarise(mean_time = mean(testelapse, na.rm = T)) %>% 
  ggplot(aes(x = education, y = mean_time)) +
  geom_col() +
  coord_flip() +
  labs(
    y = "Mean test time (s)",
    x = "Level of education"
  )
```



# 6. What’s the average RWA score for people aged
Under 18?

18 to 25?

26 to 40?

41 to 60?

Over 60?

```{r}
rwa_clean %>% 
  group_by(age_bracket) %>% 
  summarise(mean_rwa = mean(rwa, na.rm = T))
```
